FROM jboss/wildfly:10.1.0.Final
MAINTAINER George Gastaldi<ggastald@redhat.com>

# Set the BACKEND_VERSION env variable
ENV BACKEND_VERSION 1.0.0-SNAPSHOT

ADD https://repository.jboss.org/nexus/service/local/artifact/maven/redirect?r=snapshots&g=org.obsidiantoaster&a=generator-backend&v=$BACKEND_VERSION&e=war /opt/jboss/wildfly/standalone/deployments/generator-backend.war

USER root

RUN chown -R jboss:0 /opt/jboss/wildfly/standalone/deployments/ && chmod -R g+rw /opt/jboss/wildfly/standalone/deployments/

USER jboss
