FROM registry.centos.org/jboss/base-jdk:8
MAINTAINER Vasek Pavlin <vasek@redhat.com>

EXPOSE 8080
EXPOSE 8443

CMD ["java", "-jar", "generator-swarm.jar"]

USER root
RUN chgrp -R 0 $HOME &&\
    chmod -R g+r $HOME &&\
    find $HOME -type d -exec chmod g+x {} +
USER jboss

COPY target/generator-swarm.jar ./
