#!/bin/bash

# resolve links - $0 may be a softlink
PRG="$0"
while [ -h "$PRG" ]; do
    ls="$(ls -ld "$PRG")"
    link="${ls##*-> }" # remove largest prefix: yields link target (behind ->)
    if [ "$link" != "${link#/}" ]; then # remove prefix / if present
        # path was absolute
        PRG="$link"
    else
        # was not
        PRG="$(dirname "$PRG")/$link"
    fi
done
DIR="$(dirname "$PRG")"

if [ ! -f $DIR/target/creator-1-SNAPSHOT-jar-with-dependencies.jar ]; then
    (cd $DIR && mvn package)
fi

(cd $DIR && java -jar target/creator-1-SNAPSHOT-jar-with-dependencies.jar "$@")

