package io.fabric8.launcher.core.api;

import java.nio.file.Path;
import java.util.UUID;

import io.fabric8.launcher.booster.catalog.rhoar.Mission;
import io.fabric8.launcher.booster.catalog.rhoar.Runtime;
import org.immutables.value.Value;

/**
 * @author <a href="mailto:ggastald@redhat.com">George Gastaldi</a>
 */
@Value.Immutable
public interface CreateProjectile extends Projectile {

    /**
     * @return return the unique id for this projectile
     */
    @Value.Default
    @Override
    default UUID getId() {
        return UUID.randomUUID();
    }

    /**
     * @return The start of step
     */
    @Value.Default
    @Override
    default int getStartOfStep() {
        return 0;
    }

    Mission getMission();

    Runtime getRuntime();

    /**
     * @return The name to use in creating the new OpenShift project
     */
    String getOpenShiftProjectName();

    String getGitRepositoryName();

    @Value.Default
    default String getGitRepositoryDescription() {
        return "Generated by the Red Hat Developer Launch (https://developers.redhat.com/launch)";
    }


}
