package io.fabric8.launcher.core.api;

import java.nio.file.Path;
import java.util.UUID;

import io.fabric8.launcher.booster.catalog.rhoar.Mission;
import io.fabric8.launcher.booster.catalog.rhoar.Runtime;
import org.immutables.value.Value;

/**
 * Value object defining the inputs to {@link MissionControl#launch(Projectile)}
 * immutable and pre-checked for valid state during creation.
 *
 * @author <a href="mailto:alr@redhat.com">Andrew Lee Rubinger</a>
 */
@Value.Immutable
public interface Projectile {

    /**
     * @return return the unique id for this projectile
     */
    @Value.Default
    default UUID getId() {
        return UUID.randomUUID();
    }

    Path getProjectLocation();

    Mission getMission();

    Runtime getRuntime();

    /**
     * @return The name to use in creating the new OpenShift project
     */
    String getOpenShiftProjectName();

    String getGitRepositoryName();

    @Value.Default
    default String getGitRepositoryDescription() {
        return "Generated by the Red Hat Developer Launch (https://developers.redhat.com/launch)";
    }

    /**
     * @return The start of step
     */
    @Value.Default
    default int getStartOfStep() {
        return 0;
    }

//    //TODO: Move the methods below to OSIO
//    String getTargetEnvironment();
//
//    String getPipelineId();
//
//    String getSpacePath();
}