kind: Template
apiVersion: v1
parameters:
- name: LAUNCHER_MISSIONCONTROL_OPENSHIFT_TOKEN
  displayName: OpenShift token
  description: OpenShift token (leave empty when using Keycloak with OpenShift as an Identity Provider or user/password above)
  value:
- name: LAUNCHER_OAUTH_OPENSHIFT_CLIENT_ID
  displayName: OpenShift Client ID
  description:  The OpenShift Oauth Client ID to use for cluster authentication
  value: launcher
- name: LAUNCHER_OAUTH_GITHUB_CLIENT_ID
  displayName: GitHub Oauth Client ID
  description: The GitHub Oauth Client ID to use for GitHub authentication
  value:
- name: LAUNCHER_OAUTH_GITHUB_SECRET
  displayName: GitHub Oauth Secret
  description: The GitHub Oauth Secret to use for GitHub authentication
  value:
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: launcher
  stringData:
    launcher.missioncontrol.openshift.clusters.subscription.token:
    launcher.missioncontrol.openshift.token: ${LAUNCHER_MISSIONCONTROL_OPENSHIFT_TOKEN}
- apiVersion: v1
  kind: Secret
  metadata:
    name: launcher-oauth-openshift
  stringData:
    clientId: ${LAUNCHER_OAUTH_OPENSHIFT_CLIENT_ID}
- apiVersion: v1
  kind: Secret
  metadata:
    name: launcher-oauth-github
  stringData:
    clientId: ${LAUNCHER_OAUTH_GITHUB_CLIENT_ID}
    secret: ${LAUNCHER_OAUTH_GITHUB_SECRET}
