kind: Template
apiVersion: v1
metadata:
  name: launcher-configmap
  annotations:
    openshift.io/display-name: "Launcher - Configuration"
    description: This application contains the configuration settings for the Launcher
    tags: instant-app,fabric8-launcher
    iconClass: icon-shadowman
    template.openshift.io/long-description: This application contains the configuration settings for the Launcher
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://github.com/fabric8-launcher/launcher-openshift-templates
    template.openshift.io/support-url: https://access.redhat.com
labels:
  template: launcher-configmap
parameters:
- name: LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN
  displayName: Your GitHub personal access token (set at https://github.com/settings/tokens)
  description: Your GitHub personal access token (set at https://github.com/settings/tokens; leave empty when using Keycloak)
- name: LAUNCHER_MISSIONCONTROL_OPENSHIFT_API_URL
  displayName: Target OpenShift API URL
  description: The base URL of the OpenShift API where the launched boosters
    should be created (ie. https://hostname[:port] or https://ipaddress[:port]).
    Leave the default value when targetting the same OpenShift/Minishift you are
    running this on
  value: https://openshift.default.svc.cluster.local
- name: LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL
  displayName: Target OpenShift Console URL
  description: The base URL of the OpenShift Console where the launched boosters
    should be created (ie. https://hostname[:port] or https://ipaddress[:port]).
    When targetting the same OpenShift/Minishift instance you are running this on you
    can most likely look at this page's address bar of your browser and copy the URL
    Example value (https://$HOSTNAMEORIP:8443)
  value:
- name: LAUNCHER_MISSIONCONTROL_OPENSHIFT_USERNAME
  displayName: OpenShift user name
  description: OpenShift user (leave empty when using Keycloak with OpenShift as an Identity Provider or token)
  value: developer
- name: LAUNCHER_MISSIONCONTROL_OPENSHIFT_PASSWORD
  displayName: OpenShift password
  description: OpenShift password (leave empty when using Keycloak with OpenShift as an Identity Provider or token)
  value: developer
- name: LAUNCHER_MISSIONCONTROL_OPENSHIFT_IMPERSONATE_USER
  displayName: Impersonate OpenShift users
  description: Impersonate OpenShift users (requires a ServiceAccount with impersonator role)
  value:
- name: LAUNCHER_KEYCLOAK_URL
  displayName: KeyCloak URL
  description: The URL (with the /auth part) of a Keycloak installation to perform SSO
    authentication (leave empty if you've explicitly specified GItHub/OpenShift
    authentication above)
  value: https://sso.openshift.io/auth
- name: LAUNCHER_KEYCLOAK_REALM
  displayName: KeyCloak Realm
  description: The keycloak realm to be used (leave empty if you've explicitly specified
    GitHub/OpenShift authentication above)
  value: rh-developers-launch
- name: LAUNCHER_KEYCLOAK_CLIENT_ID
  displayName: KeyCloak Client ID
  description: The keycloak client id to be used in the frontend (leave empty if you've explicitly specified
    GitHub/OpenShift authentication above)
  value:
- name: LAUNCHER_OAUTH_OPENSHIFT_URL
  displayName: OpenShift OAuth Url
  description: The OpenShift Oauth Url to use for cluster authentication
- name: LAUNCHER_TRACKER_SEGMENT_TOKEN
  displayName: Segment Token
  description: The token to use for Segment tracking. Leaving this empty will disable
    tracking. This must be set to the proper tokens for staging and production!
- name: LAUNCHER_BOOSTER_CATALOG_REPOSITORY
  displayName: Catalog Git Repository
  description: The GitHub repository containing the booster catalog
  value: https://github.com/fabric8-launcher/launcher-booster-catalog.git
  required: true
- name: LAUNCHER_BOOSTER_CATALOG_REF
  displayName: Catalog Git Reference
  description: The Git reference to use for the above repository
  value: latest
  required: true
- name: LAUNCHER_BOOSTER_CATALOG_FILTER
  displayName: Catalog Filter
  description: Optional expression to filter a subset of boosters for the above repository (eg. booster.mission.id == 'rest-http')
  value:
- name: LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN
  displayName: Catalog Reindex Token
  description: A token that must be passed to the catalog reindex service to trigger the catalog
    reindexing.
  value:
- name: LAUNCHER_BACKEND_ENVIRONMENT
  displayName: Booster Environment
  description: The environment where this backend is running. This is used in the environment section
    in the booster catalog entries. Leaving this empty will set the value to 'development' if the
    'Catalog Git Reference' is set to 'master', in any other case the value will default to 'production'.
  value:
- name: LAUNCHER_BACKEND_ARTEMIS_URL
  displayName: ActiveMQ Artemis JMS URL
  description: ActiveMQ Artemis URL to store your status messages (needed when using multiple backend replicas). 
    Leave it blank if you are not planning on using more than one replica for the backend.
  value:
- name: LAUNCHER_BACKEND_ARTEMIS_USERNAME
  displayName: ActiveMQ Artemis JMS Username
  description: ActiveMQ Artemis Username for the ActiveMQ Artemis URL. Leave it blank if ActiveMQ Artemis URL is unset.
  value:
- name: LAUNCHER_BACKEND_ARTEMIS_PASSWORD
  displayName: ActiveMQ Artemis JMS Password
  description: ActiveMQ Artemis Password for the ActiveMQ Artemis URL. Leave it blank if ActiveMQ Artemis URL is unset.
  value:
- name: LAUNCHER_BACKEND_GIT_REPOSITORY_DESCRIPTION
  displayName: Git Repository Description
  description: The Git repository description to be used by Launcher
    (defaults to Generated by the Red Hat Developer Launch (https://developers.redhat.com/launch))
  value:
- name: LAUNCHER_GIT_PROVIDER
  displayName: Git Provider
  description: The Git provider to be used by Launcher (defaults to GitHub)
  value: GITHUB
- name: LAUNCHER_FILTER_RUNTIME
  displayName: Filter runtimes
  description: A regular expression that will be used to match against the id field of each runtime. You can prepend `!` in the expression to negate.
  value:
- name: LAUNCHER_FILTER_VERSION
  displayName: Filter versions
  description: A regular expression that will be used to match against the id field of each version. You can prepend `!` in the expression to negate.
  value:
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: launcher
  data:
    launcher.missioncontrol.github.token: ${LAUNCHER_MISSIONCONTROL_GITHUB_TOKEN}
    launcher.missioncontrol.openshift.username: ${LAUNCHER_MISSIONCONTROL_OPENSHIFT_USERNAME}
    launcher.missioncontrol.openshift.password: ${LAUNCHER_MISSIONCONTROL_OPENSHIFT_PASSWORD}
    launcher.missioncontrol.openshift.impersonate.user: ${LAUNCHER_MISSIONCONTROL_OPENSHIFT_IMPERSONATE_USER}
    launcher.missioncontrol.openshift.api.url: ${LAUNCHER_MISSIONCONTROL_OPENSHIFT_API_URL}
    launcher.missioncontrol.openshift.console.url: ${LAUNCHER_MISSIONCONTROL_OPENSHIFT_CONSOLE_URL}
    launcher.backend.artemis.url: ${LAUNCHER_BACKEND_ARTEMIS_URL}
    launcher.backend.artemis.username: ${LAUNCHER_BACKEND_ARTEMIS_USERNAME}
    launcher.backend.artemis.password: ${LAUNCHER_BACKEND_ARTEMIS_PASSWORD}
    launcher.backend.catalog.filter: ${LAUNCHER_BOOSTER_CATALOG_FILTER}
    launcher.backend.catalog.git.repository: ${LAUNCHER_BOOSTER_CATALOG_REPOSITORY}
    launcher.backend.catalog.git.ref: ${LAUNCHER_BOOSTER_CATALOG_REF}
    launcher.backend.catalog.reindex.token: ${LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN}
    launcher.backend.documentation.reload.token: ${LAUNCHER_BACKEND_CATALOG_REINDEX_TOKEN}
    launcher.backend.environment: ${LAUNCHER_BACKEND_ENVIRONMENT}
    launcher.backend.git.repository.description: ${LAUNCHER_BACKEND_GIT_REPOSITORY_DESCRIPTION}
    launcher.git.provider: ${LAUNCHER_GIT_PROVIDER}
    launcher.keycloak.url: ${LAUNCHER_KEYCLOAK_URL}
    launcher.keycloak.realm: ${LAUNCHER_KEYCLOAK_REALM}
    launcher.keycloak.client.id: ${LAUNCHER_KEYCLOAK_CLIENT_ID}
    launcher.oauth.openshift.url: ${LAUNCHER_OAUTH_OPENSHIFT_URL}
    launcher.tracker.segment.token: ${LAUNCHER_TRACKER_SEGMENT_TOKEN}
    launcher.backend.url: /launch/api
    launcher.filter.runtime: ${LAUNCHER_FILTER_RUNTIME}
    launcher.filter.version: ${LAUNCHER_FILTER_VERSION}
    launcher.frontend.sentry.dsn:
    launcher.frontend.targetenvironment.skip:
    launcher.backend.sentry.dsn:
    launcher.creator.enabled:
    launcher.creator.sentry.dsn:
    launcher.creator.url: /launch/creator
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: launcher-clusters
  data:
    openshift-clusters.yaml: |-
      - id: starter-us-east-1
        name: "Starter: US East (Virginia)"
        apiUrl: https://api.starter-us-east-1.openshift.com
        consoleUrl: https://console.starter-us-east-1.openshift.com
        type: starter
      - id: starter-us-west-1
        name: "Starter: US West (California)"
        apiUrl: https://api.starter-us-west-1.openshift.com
        consoleUrl: https://console.starter-us-west-1.openshift.com
        type: starter
      - id: starter-us-west-2
        name: "Starter: US West (Oregon)"
        apiUrl: https://api.starter-us-west-2.openshift.com
        consoleUrl: https://console.starter-us-west-2.openshift.com
        type: starter
      - id: starter-ca-central-1
        name: "Starter: Canada (Central)"
        apiUrl: https://api.starter-ca-central-1.openshift.com
        consoleUrl: https://console.starter-ca-central-1.openshift.com
        type: starter
      - id: pro-us-east-1
        name: "Pro: US East (N. Virginia)"
        apiUrl: https://api.pro-us-east-1.openshift.com
        consoleUrl: https://console.pro-us-east-1.openshift.com
        type: pro
      - id: pro-eu-west-1
        name: "Pro: EU West (Ireland)"
        apiUrl: https://api.pro-eu-west-1.openshift.com
        consoleUrl: https://console.pro-eu-west-1.openshift.com
        type: pro
      - id: pro-ap-southeast-2
        name: "Pro: Asia Pacific (Sydney)"
        apiUrl: https://api.pro-ap-southeast-2.openshift.com
        consoleUrl: https://console.pro-ap-southeast-2.openshift.com
        type: pro
    git-providers.yaml: |-
      - id: GitHub
        name: "GitHub"
        apiUrl: https://api.github.com
        repositoryUrl: https://github.com
        type: GITHUB
